### ISSUE TITLE
現在的 DB 可能會爛掉

### ISSUE THREAD

**Issue by AlaRduTP** [Normal-OJ/Back-End#240]
根據 #224 與 #234，修改了 DB 的 schema，可能會讓 service 爛掉。
先開個 issue 等出事的時候再修？

**Comment by Bogay** [comment]
在我本機環境發現確實巷是因為這問題壞了

```
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/workers/gthread.py", line 92, in init_process
    super().init_process()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/gunicorn/util.py", line 412, in import_app
    app = app(*args, **kwargs)
  File "/app/app.py", line 52, in app
    if not Course('Public'):
  File "/app/mongo/course.py", line 28, in __new__
    pk = Course.engine.objects(course_name=course_name).get()
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 269, in get
    result = next(queryset)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/mongoengine/queryset/base.py", line 1599, in __next__
    doc = self._document._from_son(
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 836, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/mongoengine/base/document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'contests'}" do not exist on the document "Course"
```

**Comment by aokblast** [comment]
Does this issue fixed in the migration?

**Comment by Bogay** [comment]
雀食

Closed via #278
